module.exports = {
  clearMocks: true,
  extensionsToTreatAsEsm: [".ts"],
  moduleFileExtensions: ["js", "json", "ts"],
  preset: "ts-jest/presets/default-esm",
  rootDir: ".",
  testEnvironment: "node",
  testMatch: ["<rootDir>/src/**/*.spec.ts"],
  moduleNameMapper: {
    "^@agent-log-search/shared$": "<rootDir>/../../packages/shared/src/index.ts",
    "^\\./constants\\.js$": "<rootDir>/../../packages/shared/src/constants.ts",
    "^\\./domain\\.js$": "<rootDir>/../../packages/shared/src/domain.ts",
    "^\\./errors\\.js$": "<rootDir>/../../packages/shared/src/errors.ts",
    "^\\./pagination\\.js$": "<rootDir>/../../packages/shared/src/pagination.ts",
    "^\\./search\\.js$": "<rootDir>/../../packages/shared/src/search.ts",
    "^\\./sources\\.js$": "<rootDir>/../../packages/shared/src/sources.ts",
    "^\\./app\\.module\\.js$": "<rootDir>/src/app.module.ts",
    "^\\./bootstrap\\.js$": "<rootDir>/src/bootstrap.ts",
    "^\\./database-url\\.js$": "<rootDir>/src/database/database-url.ts",
    "^\\./database/(.*)\\.js$": "<rootDir>/src/database/$1.ts",
    "^\\.\\./database/(.*)\\.js$": "<rootDir>/src/database/$1.ts",
    "^\\./health\\.controller\\.js$": "<rootDir>/src/health.controller.ts",
    "^\\./pg\\.service\\.js$": "<rootDir>/src/database/pg.service.ts",
    "^\\./prisma\\.service\\.js$": "<rootDir>/src/database/prisma.service.ts",
    "^\\./scan-jobs/(.*)\\.js$": "<rootDir>/src/scan-jobs/$1.ts",
    "^\\.\\./scan-jobs/(.*)\\.js$": "<rootDir>/src/scan-jobs/$1.ts",
    "^\\./(history-files\\.service|record-readers|scan-job-mapping|scan-jobs\\.controller|scan-jobs\\.module|scan-jobs\\.service)\\.js$":
      "<rootDir>/src/scan-jobs/$1.ts",
    "^\\./source-mapping\\.js$": "<rootDir>/src/sources/source-mapping.ts",
    "^\\./sources/(.*)\\.js$": "<rootDir>/src/sources/$1.ts",
    "^\\.\\./sources/(.*)\\.js$": "<rootDir>/src/sources/$1.ts",
    "^\\./path-policy\\.service\\.js$": "<rootDir>/src/sources/path-policy.service.ts",
    "^\\./sources\\.controller\\.js$": "<rootDir>/src/sources/sources.controller.ts",
    "^\\./sources\\.module\\.js$": "<rootDir>/src/sources/sources.module.ts",
    "^\\./sources\\.service\\.js$": "<rootDir>/src/sources/sources.service.ts",
    "^\\./zod-validation\\.pipe\\.js$": "<rootDir>/src/sources/zod-validation.pipe.ts",
  },
  transform: {
    "^.+\\.ts$": [
      "ts-jest",
      {
        tsconfig: "<rootDir>/tsconfig.json",
        useESM: true,
      },
    ],
  },
}
