module.exports = {
  clearMocks: true,
  extensionsToTreatAsEsm: [".ts"],
  moduleFileExtensions: ["js", "json", "ts"],
  preset: "ts-jest/presets/default-esm",
  rootDir: ".",
  testEnvironment: "node",
  testMatch: ["<rootDir>/src/**/*.spec.ts"],
  moduleNameMapper: {
    "^@agent-log-search/shared$": "<rootDir>/../../packages/shared/src/index.ts",
    "^\\./constants\\.js$": "<rootDir>/../../packages/shared/src/constants.ts",
    "^\\./domain\\.js$": "<rootDir>/../../packages/shared/src/domain.ts",
    "^\\./embeddings\\.js$": "<rootDir>/../../packages/shared/src/embeddings.ts",
    "^\\./errors\\.js$": "<rootDir>/../../packages/shared/src/errors.ts",
    "^\\./evidence\\.js$": "<rootDir>/../../packages/shared/src/evidence.ts",
    "^\\./experiences\\.js$": "<rootDir>/../../packages/shared/src/experiences.ts",
    "^\\./pagination\\.js$": "<rootDir>/../../packages/shared/src/pagination.ts",
    "^\\./search\\.js$": "<rootDir>/../../packages/shared/src/search.ts",
    "^\\./sources\\.js$": "<rootDir>/../../packages/shared/src/sources.ts",
    "^\\./app\\.module\\.js$": "<rootDir>/src/app.module.ts",
    "^\\./bootstrap\\.js$": "<rootDir>/src/bootstrap.ts",
    "^\\./database-url\\.js$": "<rootDir>/src/database/database-url.ts",
    "^\\./database/(.*)\\.js$": "<rootDir>/src/database/$1.ts",
    "^\\.\\./database/(.*)\\.js$": "<rootDir>/src/database/$1.ts",
    "^\\./env-file-config\\.js$": "<rootDir>/src/env-file-config.ts",
    "^\\./evidence/(.*)\\.js$": "<rootDir>/src/evidence/$1.ts",
    "^\\.\\./evidence/(.*)\\.js$": "<rootDir>/src/evidence/$1.ts",
    "^\\./(command|errors|paths|patches|validation|redaction|excerpt)/(.*)\\.js$":
      "<rootDir>/src/evidence/$1/$2.ts",
    "^\\.\\./(command|errors|paths|patches|validation|redaction|excerpt)/(.*)\\.js$":
      "<rootDir>/src/evidence/$1/$2.ts",
    "^\\./(command-classifier|command-extractor|shell-tokenizer)\\.js$":
      "<rootDir>/src/evidence/command/$1.ts",
    "^\\./(error-extractor|error-fingerprint|error-normalizer)\\.js$":
      "<rootDir>/src/evidence/errors/$1.ts",
    "^\\./(path-extractor|path-normalizer)\\.js$": "<rootDir>/src/evidence/paths/$1.ts",
    "^\\./(patch-parser)\\.js$": "<rootDir>/src/evidence/patches/$1.ts",
    "^\\./(generic-process-parser|go-test-output-parser|jest-output-parser|pytest-output-parser|validation-output-parser|vitest-output-parser)\\.js$":
      "<rootDir>/src/evidence/validation/$1.ts",
    "^\\./(secret-redactor)\\.js$": "<rootDir>/src/evidence/redaction/$1.ts",
    "^\\./(evidence-excerpt-builder)\\.js$": "<rootDir>/src/evidence/excerpt/$1.ts",
    "^\\./(canonical-tool-classifier|evidence[^/]*|fixture-shape-inventory)\\.js$":
      "<rootDir>/src/evidence/$1.ts",
    "^\\./experience-search/(.*)\\.js$": "<rootDir>/src/experience-search/$1.ts",
    "^\\.\\./experience-search/(.*)\\.js$": "<rootDir>/src/experience-search/$1.ts",
    "^\\./(experience-ranker|experience-search\\.(?:controller|module|service)|failed-attempt-search\\.service|query-feature-extractor)\\.js$":
      "<rootDir>/src/experience-search/$1.ts",
    "^\\./experiences/(.*)\\.js$": "<rootDir>/src/experiences/$1.ts",
    "^\\.\\./experiences/(.*)\\.js$": "<rootDir>/src/experiences/$1.ts",
    "^\\./(attempt-builder|episode-segmenter|experiences\\.module|experience\\.config|experience-worker|experience-claim-store|experience-persistence\\.service|experience-builder|experience\\.types)\\.js$":
      "<rootDir>/src/experiences/$1.ts",
    "^\\./health\\.controller\\.js$": "<rootDir>/src/health.controller.ts",
    "^\\./(message-parts)\\.js$": "<rootDir>/src/messages/$1.ts",
    "^\\./pipeline-versions\\.js$": "<rootDir>/src/pipeline-versions.ts",
    "^\\.\\./pipeline-versions\\.js$": "<rootDir>/src/pipeline-versions.ts",
    "^\\./(compatibility\\.service|git-inspector\\.service|repositories\\.module|repository-locator\\.service|repository-path-policy\\.service|repository-snapshot\\.service|repository\\.types)\\.js$":
      "<rootDir>/src/repositories/$1.ts",
    "^\\./repositories/(.*)\\.js$": "<rootDir>/src/repositories/$1.ts",
    "^\\.\\./repositories/(.*)\\.js$": "<rootDir>/src/repositories/$1.ts",
    "^\\./messages/(.*)\\.js$": "<rootDir>/src/messages/$1.ts",
    "^\\.\\./messages/(.*)\\.js$": "<rootDir>/src/messages/$1.ts",
    "^\\./embeddings/(.*)\\.js$": "<rootDir>/src/embeddings/$1.ts",
    "^\\.\\./embeddings/(.*)\\.js$": "<rootDir>/src/embeddings/$1.ts",
    "^\\./(embedding[^/]*|embeddings[^/]*)\\.js$": "<rootDir>/src/embeddings/$1.ts",
    "^\\./fixture-(metadata|validation-support)\\.js$": "<rootDir>/src/fixtures/fixture-$1.ts",
    "^\\./parsers-test-support\\.js$": "<rootDir>/src/parsers-test-support.ts",
    "^\\./parsers/(.*)\\.js$": "<rootDir>/src/parsers/$1.ts",
    "^\\.\\./parsers/(.*)\\.js$": "<rootDir>/src/parsers/$1.ts",
    "^\\.\\.\\/\\.\\.\\/parsers/(.*)\\.js$": "<rootDir>/src/parsers/$1.ts",
    "^\\./(agent-jsonl-parsers|content-normalizer|generic-json-parsers|generic-markdown-parser|json-parse|jsonl-reader|opencode-sqlite-parser|parser-errors|parser-registry|parser-types|record-access|session-builder|source-guards|source-readers|trace-event-builders)\\.js$":
      "<rootDir>/src/parsers/$1.ts",
    "^\\./pg\\.service\\.js$": "<rootDir>/src/database/pg.service.ts",
    "^\\./prisma\\.service\\.js$": "<rootDir>/src/database/prisma.service.ts",
    "^\\./scanner/(.*)\\.js$": "<rootDir>/src/scanner/$1.ts",
    "^\\.\\./scanner/(.*)\\.js$": "<rootDir>/src/scanner/$1.ts",
    "^\\./chunker\\.service\\.js$": "<rootDir>/src/scanner/chunker.service.ts",
    "^\\./scan\\.controller\\.js$": "<rootDir>/src/scanner/scan.controller.ts",
    "^\\./(message-retention|scanner[^/]*|source-reader-registry)\\.js$":
      "<rootDir>/src/scanner/$1.ts",
    "^\\./search/(.*)\\.js$": "<rootDir>/src/search/$1.ts",
    "^\\.\\./search/(.*)\\.js$": "<rootDir>/src/search/$1.ts",
    "^\\./(search[^/]*)\\.js$": "<rootDir>/src/search/$1.ts",
    "^\\./sessions/(.*)\\.js$": "<rootDir>/src/sessions/$1.ts",
    "^\\.\\./sessions/(.*)\\.js$": "<rootDir>/src/sessions/$1.ts",
    "^\\./(session[^/]*|sessions[^/]*)\\.js$": "<rootDir>/src/sessions/$1.ts",
    "^\\./scan-jobs/(.*)\\.js$": "<rootDir>/src/scan-jobs/$1.ts",
    "^\\.\\./scan-jobs/(.*)\\.js$": "<rootDir>/src/scan-jobs/$1.ts",
    "^\\./traces/(.*)\\.js$": "<rootDir>/src/traces/$1.ts",
    "^\\.\\./traces/(.*)\\.js$": "<rootDir>/src/traces/$1.ts",
    "^\\./(tool-exchange[^/]*)\\.js$": "<rootDir>/src/traces/$1.ts",
    "^\\./(history-files\\.service|record-readers|scan-job-mapping|scan-jobs\\.controller|scan-jobs\\.module|scan-jobs\\.service)\\.js$":
      "<rootDir>/src/scan-jobs/$1.ts",
    "^\\./source-mapping\\.js$": "<rootDir>/src/sources/source-mapping.ts",
    "^\\./sources/(.*)\\.js$": "<rootDir>/src/sources/$1.ts",
    "^\\.\\./sources/(.*)\\.js$": "<rootDir>/src/sources/$1.ts",
    "^\\./path-policy\\.service\\.js$": "<rootDir>/src/sources/path-policy.service.ts",
    "^\\./sources\\.controller\\.js$": "<rootDir>/src/sources/sources.controller.ts",
    "^\\./sources\\.module\\.js$": "<rootDir>/src/sources/sources.module.ts",
    "^\\./sources\\.service\\.js$": "<rootDir>/src/sources/sources.service.ts",
    "^\\./zod-validation\\.pipe\\.js$": "<rootDir>/src/sources/zod-validation.pipe.ts",
  },
  transform: {
    "^.+\\.ts$": [
      "ts-jest",
      {
        tsconfig: "<rootDir>/tsconfig.json",
        useESM: true,
      },
    ],
  },
}
